# Generated by Django 2.2.5 on 2019-09-14 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_access', models.CharField(max_length=10)),
                ('space_name', models.CharField(max_length=35)),
                ('space_password', models.CharField(max_length=256)),
                ('space_category', models.CharField(blank=True, max_length=256)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=50)),
                ('post_title', models.CharField(max_length=50)),
                ('post_contents', models.TextField(blank=True, help_text='글 내용')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('space_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='space.Space')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
