# Generated by Django 2.2.5 on 2019-09-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='space_id',
            new_name='space',
        ),
    ]
