# Generated by Django 2.2.5 on 2019-09-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20190914_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
